version: '2'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    environment:
      - MYSQL_HOST=db
      - PROXY_REST=restjs
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
  
  restjs:
    build: ./restjs
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
    - .:/home/node/restjs 
    expose:
      # Opens port 3001 on the container
      - '3001'  
   

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'nodelogin'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3005:3306'
    expose:
      # Opens port 3306 on the container
      - '3005'
      # Where our data will be persisted
    
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"

